# Generated by Django 3.1.7 on 2021-03-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210302_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_offer',
            field=models.BooleanField(default=False),
        ),
    ]
