# Generated by Django 3.1.7 on 2021-03-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_has_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
